### ISSUE TITLE
get_stops_coordinates(route_id) and documentation

### ISSUE THREAD

**Issue by pavelponomarev** [araichev/gtfstk#1]
Hi,

I need to make a function of getting coordinates of stops along a route. It will take for me a couple of hours, maybe you have such a function already implemented? Where can I find the documentation like list of functions and their descriptions?

BR, Pavel

**Comment by araichev** [comment]
Hello Pavel, the docs are linked to on the project's Github landing page (https://github.com/araichev/gtfstk).  No single GTFSTK function will help you with your task. Maybe i should add one to the package. 

Regarding your task, suppose your route ID is stored as ``rid`` and your feed has been loaded from a GTFS file via ``read_gtfs()`` as ``feed``.
Then the following code snippet yields the slice of ``feed.stops`` corresponding to the stops or your route.
That slice contains all basic stop information, such as geographic coordinates.

    # Get the IDs of the trips on the route
    trips = feed.trips[feed.trips['route_id'] == rid]
    tids = trips['trip_id']
    # Get the IDs of the stops on those trips 
    stop_times = feed.stop_times[feed.stop_times['trip_id'].isin(tids)]
    sids = stop_times['stop_id'].unique()
    # Get the section of ``feed.stops`` with those stop IDs
    stops = feed.stops[feed.stops['stop_id'].isin(sids)]
