### ISSUE TITLE
All GeoJSONs load error

### ISSUE THREAD

**Issue by kuanb** [araichev/gtfstk#6]
I know these are different projects but I saw your comment from Transit Land and wanted to see what you had done with your GTFS tool which I assume is what is underpinning the GTFS Explorer:

Since I couldn't find you on Twitter and your blog has no comments - I am hoping here is ok!

The load GeoJSONs 500s on the demo account on the Explorer site:
![image](https://user-images.githubusercontent.com/6053396/28441649-b819ce44-6d60-11e7-9552-62a6ef40a452.png)

**Comment by araichev** [comment]
Thanks for the bug report, @kuanb.
Looks like i forgot to update the Cairns route shapes in the database when i updated its stats in GTFS Explorer last week.
Fixed now.

Yes, GTFS Explorer use GTFSTK to compute stats.  
It also uses [django-multi-gtfs](https://github.com/tulsawebdevs/django-multi-gtfs) to store routes etc. in a PostGIS database.
